KUI-1388: Updated api to handle recommended prerequisites
KTH/kursinfo-api pull request #267
Opened 2024-08-14 13:35 UTC by axelbjo

Note: Do not merge this

2024-08-15 06:20 UTC, karlandindrakryggen requested changes
Look into the failing integration test and revert updates in import script.

2024-08-15 06:20 UTC, karlandindrakryggen commented on scripts/importData/index.js
> +    'recommendedPrerequisites_en',
I'm not sure, but I think we need to create a new import script for just recommendedPrerequisites_sv/en. But for now I think we can wait with that, ie not updating importData/index.js and importData/index2.js at all

2024-08-15 06:56 UTC, karlandindrakryggen approved these changes

2024-08-15 06:56 UTC, karlandindrakryggen commented
Remember to not merge this for now (needs to be synced with release of changes in other repos)

2024-08-15 06:57 UTC, axelbjo commented on docker-compose-integration-tests.yml
This is deprecated and is not needed any longer

https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313

2024-08-16 09:29 UTC, amirhossein-haerian approved these changes
LGTM, Great Job ⭐️

2024-08-23 06:57 UTC, allazis approved these changes
Good job!

2024-10-04 08:39 UTC, merged